import fs from "node:fs";
import path from "node:path";

// Default entries for a Node.js/React .gitignore
const DEFAULT_GITIGNORE_CONTENT = `
# Dependencies
/node_modules
/.pnp
.pnp.js

# Build artifacts
/build
/dist
.next/

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
.env.*

# IDEs and editors
.vscode/
.idea/
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# OS-generated files
.DS_Store
Thumbs.db

# Test reports
/coverage
/reports
`;

// AI tool-specific entries to be ignored
const AI_TOOL_ENTRIES = ["/.claude/", "/.gemini/", "/.taskmaster/", "/.mcp.json"];

/**
 * Ensures .gitignore exists and contains entries for AI tools.
 * @param {string} projectDir The user's project root directory.
 */
export function setupGitignore(projectDir = process.cwd()) {
    const gitignorePath = path.join(projectDir, ".gitignore");

    if (!fs.existsSync(gitignorePath)) {
        // .gitignore doesn't exist, create a new one with full template
        console.log("  Creating new .gitignore file with default settings...");
        const header = "# Auto-generated .gitignore file\n";
        const aiHeader = "\n# AI Tools Configuration (generated by @rueda.dev/config)\n";
        const newContent = header + DEFAULT_GITIGNORE_CONTENT + aiHeader + AI_TOOL_ENTRIES.join("\n") + "\n";

        fs.writeFileSync(gitignorePath, newContent, "utf-8");
        console.log("  .gitignore created successfully.");
    } else {
        // .gitignore already exists, check and add only missing entries
        let content = fs.readFileSync(gitignorePath, "utf-8");
        const entriesToAdd = [];

        for (const entry of AI_TOOL_ENTRIES) {
            // Check if the exact entry already exists in the file
            const entryRegex = new RegExp(`^${entry.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, "m");
            if (!entryRegex.test(content)) {
                entriesToAdd.push(entry);
            }
        }

        if (entriesToAdd.length > 0) {
            console.log("  Updating .gitignore with AI tools configuration...");
            const aiHeader = "\n# AI Tools Configuration (generated by @rueda.dev/config)\n";
            const contentToAppend = aiHeader + entriesToAdd.join("\n") + "\n";

            fs.appendFileSync(gitignorePath, contentToAppend, "utf-8");
            console.log("  .gitignore updated.");
        } else {
            console.log("  AI tools entries already exist in .gitignore. No changes needed.");
        }
    }
}
